# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/joaovitorwolfart/Dropbox/JP/PROJETO SALÃO/telas_duda/estatisticas_ag_futuro.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1220, 850)
        MainWindow.setMinimumSize(QtCore.QSize(1220, 850))
        MainWindow.setMaximumSize(QtCore.QSize(1220, 850))
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(215, 139, 185);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_id_user = QtWidgets.QLabel(self.centralwidget)
        self.lbl_id_user.setGeometry(QtCore.QRect(1140, 70, 41, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_id_user.setFont(font)
        self.lbl_id_user.setStyleSheet("color: rgb(62, 132, 238);")
        self.lbl_id_user.setText("")
        self.lbl_id_user.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_id_user.setObjectName("lbl_id_user")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 210, 1201, 631))
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setStyleSheet("background-color: rgb(255, 231, 249);")
        self.tabWidget.setObjectName("tabWidget")
        self.tabVendas = QtWidgets.QWidget()
        self.tabVendas.setObjectName("tabVendas")
        self.frame_2 = QtWidgets.QFrame(self.tabVendas)
        self.frame_2.setGeometry(QtCore.QRect(20, 490, 1151, 80))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lbl_total = QtWidgets.QLabel(self.frame_2)
        self.lbl_total.setGeometry(QtCore.QRect(20, 20, 1061, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.lbl_total.setFont(font)
        self.lbl_total.setStyleSheet("color: rgb(115, 210, 22);")
        self.lbl_total.setText("")
        self.lbl_total.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_total.setObjectName("lbl_total")
        self.TabelaVendasDia = QtWidgets.QTableWidget(self.tabVendas)
        self.TabelaVendasDia.setEnabled(True)
        self.TabelaVendasDia.setGeometry(QtCore.QRect(10, 70, 1161, 411))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TabelaVendasDia.sizePolicy().hasHeightForWidth())
        self.TabelaVendasDia.setSizePolicy(sizePolicy)
        self.TabelaVendasDia.setMinimumSize(QtCore.QSize(465, 0))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(13)
        self.TabelaVendasDia.setFont(font)
        self.TabelaVendasDia.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.TabelaVendasDia.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.TabelaVendasDia.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.TabelaVendasDia.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.TabelaVendasDia.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.TabelaVendasDia.setObjectName("TabelaVendasDia")
        self.TabelaVendasDia.setColumnCount(2)
        self.TabelaVendasDia.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaVendasDia.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaVendasDia.setHorizontalHeaderItem(1, item)
        self.TabelaVendasDia.horizontalHeader().setDefaultSectionSize(150)
        self.TabelaVendasDia.horizontalHeader().setSortIndicatorShown(False)
        self.TabelaVendasDia.horizontalHeader().setStretchLastSection(True)
        self.TabelaVendasDia.verticalHeader().setSortIndicatorShown(False)
        self.label_9 = QtWidgets.QLabel(self.tabVendas)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 1021, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.tabWidget.addTab(self.tabVendas, "")
        self.tabServicos = QtWidgets.QWidget()
        self.tabServicos.setObjectName("tabServicos")
        self.frame_3 = QtWidgets.QFrame(self.tabServicos)
        self.frame_3.setGeometry(QtCore.QRect(10, 500, 1161, 80))
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.lbl_total_servicos = QtWidgets.QLabel(self.frame_3)
        self.lbl_total_servicos.setGeometry(QtCore.QRect(20, 20, 1061, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.lbl_total_servicos.setFont(font)
        self.lbl_total_servicos.setStyleSheet("color: rgb(115, 210, 22);")
        self.lbl_total_servicos.setText("")
        self.lbl_total_servicos.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_total_servicos.setObjectName("lbl_total_servicos")
        self.label_4 = QtWidgets.QLabel(self.tabServicos)
        self.label_4.setGeometry(QtCore.QRect(60, 10, 1021, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.TabelaServicos = QtWidgets.QTableWidget(self.tabServicos)
        self.TabelaServicos.setEnabled(True)
        self.TabelaServicos.setGeometry(QtCore.QRect(10, 70, 1171, 411))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TabelaServicos.sizePolicy().hasHeightForWidth())
        self.TabelaServicos.setSizePolicy(sizePolicy)
        self.TabelaServicos.setMinimumSize(QtCore.QSize(465, 0))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(13)
        self.TabelaServicos.setFont(font)
        self.TabelaServicos.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.TabelaServicos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.TabelaServicos.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.TabelaServicos.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.TabelaServicos.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.TabelaServicos.setObjectName("TabelaServicos")
        self.TabelaServicos.setColumnCount(4)
        self.TabelaServicos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.TabelaServicos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaServicos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaServicos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaServicos.setHorizontalHeaderItem(3, item)
        self.TabelaServicos.horizontalHeader().setDefaultSectionSize(165)
        self.TabelaServicos.horizontalHeader().setSortIndicatorShown(False)
        self.TabelaServicos.horizontalHeader().setStretchLastSection(True)
        self.TabelaServicos.verticalHeader().setSortIndicatorShown(False)
        self.tabWidget.addTab(self.tabServicos, "")
        self.tabClientes = QtWidgets.QWidget()
        self.tabClientes.setObjectName("tabClientes")
        self.frame_4 = QtWidgets.QFrame(self.tabClientes)
        self.frame_4.setGeometry(QtCore.QRect(20, 500, 1121, 80))
        self.frame_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.lbl_total_clientes = QtWidgets.QLabel(self.frame_4)
        self.lbl_total_clientes.setGeometry(QtCore.QRect(20, 20, 1061, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.lbl_total_clientes.setFont(font)
        self.lbl_total_clientes.setStyleSheet("color: rgb(115, 210, 22);")
        self.lbl_total_clientes.setText("")
        self.lbl_total_clientes.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_total_clientes.setObjectName("lbl_total_clientes")
        self.TabelaClientes = QtWidgets.QTableWidget(self.tabClientes)
        self.TabelaClientes.setEnabled(True)
        self.TabelaClientes.setGeometry(QtCore.QRect(20, 70, 1131, 421))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TabelaClientes.sizePolicy().hasHeightForWidth())
        self.TabelaClientes.setSizePolicy(sizePolicy)
        self.TabelaClientes.setMinimumSize(QtCore.QSize(465, 0))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(13)
        self.TabelaClientes.setFont(font)
        self.TabelaClientes.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.TabelaClientes.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.TabelaClientes.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.TabelaClientes.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.TabelaClientes.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.TabelaClientes.setObjectName("TabelaClientes")
        self.TabelaClientes.setColumnCount(5)
        self.TabelaClientes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaClientes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaClientes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaClientes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaClientes.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaClientes.setHorizontalHeaderItem(4, item)
        self.TabelaClientes.horizontalHeader().setDefaultSectionSize(150)
        self.TabelaClientes.horizontalHeader().setSortIndicatorShown(False)
        self.TabelaClientes.horizontalHeader().setStretchLastSection(True)
        self.TabelaClientes.verticalHeader().setSortIndicatorShown(False)
        self.label_6 = QtWidgets.QLabel(self.tabClientes)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 1021, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.tabClientes, "")
        self.tabProfissionais = QtWidgets.QWidget()
        self.tabProfissionais.setObjectName("tabProfissionais")
        self.frame_5 = QtWidgets.QFrame(self.tabProfissionais)
        self.frame_5.setGeometry(QtCore.QRect(10, 480, 1141, 80))
        self.frame_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.lbl_total_profi = QtWidgets.QLabel(self.frame_5)
        self.lbl_total_profi.setGeometry(QtCore.QRect(20, 20, 1061, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.lbl_total_profi.setFont(font)
        self.lbl_total_profi.setStyleSheet("color: rgb(115, 210, 22);")
        self.lbl_total_profi.setText("")
        self.lbl_total_profi.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_total_profi.setObjectName("lbl_total_profi")
        self.TabelaProfi = QtWidgets.QTableWidget(self.tabProfissionais)
        self.TabelaProfi.setEnabled(True)
        self.TabelaProfi.setGeometry(QtCore.QRect(10, 70, 1151, 401))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TabelaProfi.sizePolicy().hasHeightForWidth())
        self.TabelaProfi.setSizePolicy(sizePolicy)
        self.TabelaProfi.setMinimumSize(QtCore.QSize(465, 0))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(13)
        self.TabelaProfi.setFont(font)
        self.TabelaProfi.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.TabelaProfi.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.TabelaProfi.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.TabelaProfi.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.TabelaProfi.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.TabelaProfi.setObjectName("TabelaProfi")
        self.TabelaProfi.setColumnCount(5)
        self.TabelaProfi.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaProfi.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaProfi.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaProfi.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaProfi.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaProfi.setHorizontalHeaderItem(4, item)
        self.TabelaProfi.horizontalHeader().setDefaultSectionSize(150)
        self.TabelaProfi.horizontalHeader().setSortIndicatorShown(False)
        self.TabelaProfi.horizontalHeader().setStretchLastSection(True)
        self.TabelaProfi.verticalHeader().setSortIndicatorShown(False)
        self.label_7 = QtWidgets.QLabel(self.tabProfissionais)
        self.label_7.setGeometry(QtCore.QRect(60, 10, 1021, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.tabWidget.addTab(self.tabProfissionais, "")
        self.tabCancelados = QtWidgets.QWidget()
        self.tabCancelados.setObjectName("tabCancelados")
        self.TabelaCancelados = QtWidgets.QTableWidget(self.tabCancelados)
        self.TabelaCancelados.setEnabled(True)
        self.TabelaCancelados.setGeometry(QtCore.QRect(10, 70, 1161, 371))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TabelaCancelados.sizePolicy().hasHeightForWidth())
        self.TabelaCancelados.setSizePolicy(sizePolicy)
        self.TabelaCancelados.setMinimumSize(QtCore.QSize(465, 0))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(13)
        self.TabelaCancelados.setFont(font)
        self.TabelaCancelados.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.TabelaCancelados.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.TabelaCancelados.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.TabelaCancelados.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.TabelaCancelados.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.TabelaCancelados.setObjectName("TabelaCancelados")
        self.TabelaCancelados.setColumnCount(4)
        self.TabelaCancelados.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaCancelados.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaCancelados.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaCancelados.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaCancelados.setHorizontalHeaderItem(3, item)
        self.TabelaCancelados.horizontalHeader().setDefaultSectionSize(150)
        self.TabelaCancelados.horizontalHeader().setSortIndicatorShown(False)
        self.TabelaCancelados.horizontalHeader().setStretchLastSection(True)
        self.TabelaCancelados.verticalHeader().setSortIndicatorShown(False)
        self.label_8 = QtWidgets.QLabel(self.tabCancelados)
        self.label_8.setGeometry(QtCore.QRect(20, 10, 1161, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_5 = QtWidgets.QLabel(self.tabCancelados)
        self.label_5.setGeometry(QtCore.QRect(800, 440, 331, 111))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("/home/joaovitorwolfart/Dropbox/JP/PROJETO SALÃO/telas_duda/../IMAGENS/PicsArt_10-18-10.18.32.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.tabCancelados, "")
        self.DataInicial = QtWidgets.QDateEdit(self.centralwidget)
        self.DataInicial.setGeometry(QtCore.QRect(400, 160, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(21)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.DataInicial.setFont(font)
        self.DataInicial.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border-color: rgb(0,0,0);\n"
"font: 21pt \"Ubuntu\";\n"
"color: black;\n"
"")
        self.DataInicial.setAlignment(QtCore.Qt.AlignCenter)
        self.DataInicial.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 1, 1), QtCore.QTime(0, 0, 0)))
        self.DataInicial.setCalendarPopup(True)
        self.DataInicial.setTimeSpec(QtCore.Qt.LocalTime)
        self.DataInicial.setObjectName("DataInicial")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 160, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.DataFinal = QtWidgets.QDateEdit(self.centralwidget)
        self.DataFinal.setGeometry(QtCore.QRect(700, 160, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(21)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.DataFinal.setFont(font)
        self.DataFinal.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border-color: rgb(0,0,0);\n"
"font: 21pt \"Ubuntu\";\n"
"color: black;\n"
"")
        self.DataFinal.setAlignment(QtCore.Qt.AlignCenter)
        self.DataFinal.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 1, 1), QtCore.QTime(0, 0, 0)))
        self.DataFinal.setCalendarPopup(True)
        self.DataFinal.setTimeSpec(QtCore.Qt.LocalTime)
        self.DataFinal.setObjectName("DataFinal")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(610, 160, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(120, 100, 1061, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.BtnCarregar = QtWidgets.QPushButton(self.centralwidget)
        self.BtnCarregar.setGeometry(QtCore.QRect(960, 150, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.BtnCarregar.setFont(font)
        self.BtnCarregar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BtnCarregar.setStyleSheet("QPushButton {     \n"
"    background-color:rgb(78, 154, 6);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    \n"
"}\n"
"QPushButton:hover {   \n"
"    background-color:rgb(85, 165, 10);\n"
"}")
        self.BtnCarregar.setObjectName("BtnCarregar")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(180, 30, 911, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_11.setObjectName("label_11")
        self.lbl_id_user.raise_()
        self.tabWidget.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.DataInicial.raise_()
        self.DataFinal.raise_()
        self.label_10.raise_()
        self.BtnCarregar.raise_()
        self.label_11.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Previsões futuras baseado nos agendamentos"))
        self.TabelaVendasDia.setSortingEnabled(False)
        item = self.TabelaVendasDia.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Data prevista"))
        item = self.TabelaVendasDia.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Total Previsto"))
        self.label_9.setText(_translate("MainWindow", "Previsão de  faturamento futuro por dia com base nos agendamentos (valor bruto)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabVendas), _translate("MainWindow", "Previsão por dia"))
        self.label_4.setText(_translate("MainWindow", "Previsão de  faturamento futuro por serviço com base nos agendamentos (valor bruto)"))
        self.TabelaServicos.setSortingEnabled(False)
        item = self.TabelaServicos.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Posição no ranking"))
        item = self.TabelaServicos.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Quant"))
        item = self.TabelaServicos.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Serviço"))
        item = self.TabelaServicos.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Total bruto previsto"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabServicos), _translate("MainWindow", "Previsão por serviço"))
        self.TabelaClientes.setSortingEnabled(False)
        item = self.TabelaClientes.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Posição no ranking"))
        item = self.TabelaClientes.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nome do cliente"))
        item = self.TabelaClientes.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Quant serviços previstos"))
        item = self.TabelaClientes.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Total bruto previsto"))
        item = self.TabelaClientes.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Fidelizado"))
        self.label_6.setText(_translate("MainWindow", "Previsão de  faturamento futuro por cliente com base nos agendamentos (valor bruto)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabClientes), _translate("MainWindow", "Previsão por cliente"))
        self.TabelaProfi.setSortingEnabled(False)
        item = self.TabelaProfi.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Posição no ranking"))
        item = self.TabelaProfi.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "N° de atendimentos previsto"))
        item = self.TabelaProfi.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Nome do profissional"))
        item = self.TabelaProfi.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Especialidade"))
        item = self.TabelaProfi.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Total bruto previsto"))
        self.label_7.setText(_translate("MainWindow", "Previsão de  faturamento futuro por profissional com base nos agendamentos (valor bruto)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabProfissionais), _translate("MainWindow", "Previsão por profissionais"))
        self.TabelaCancelados.setSortingEnabled(False)
        item = self.TabelaCancelados.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nome do cliente"))
        item = self.TabelaCancelados.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "N° de cancelamentos"))
        item = self.TabelaCancelados.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Fidelizado"))
        item = self.TabelaCancelados.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Motivo do cancelamento"))
        self.label_8.setText(_translate("MainWindow", "Todos os cancelamentos ou faltas dos clientes (não apenas do intervalo de datas)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCancelados), _translate("MainWindow", "Lista negra de clientes"))
        self.label.setText(_translate("MainWindow", "Data inicial:"))
        self.label_2.setText(_translate("MainWindow", "Data final:"))
        self.label_10.setText(_translate("MainWindow", "Selecione o intervalo de datas que deseja ver a previsão futura baseada na agenda"))
        self.BtnCarregar.setText(_translate("MainWindow", "Carregar tabelas"))
        self.label_11.setText(_translate("MainWindow", "Previsões futuras baseado nos agendamentos - estatisticas:"))
