# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/joaovitorwolfart/Dropbox/JP/PROJETO SALÃO/telas_duda/nf_agenda.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1391, 663)
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(52, 101, 164);\n"
"background-color: rgb(255, 231, 249);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_id_user = QtWidgets.QLabel(self.centralwidget)
        self.lbl_id_user.setGeometry(QtCore.QRect(1080, 30, 41, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_id_user.setFont(font)
        self.lbl_id_user.setStyleSheet("color: rgb(62, 132, 238);")
        self.lbl_id_user.setText("")
        self.lbl_id_user.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_id_user.setObjectName("lbl_id_user")
        self.lbl_dia = QtWidgets.QLabel(self.centralwidget)
        self.lbl_dia.setGeometry(QtCore.QRect(40, 90, 1121, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_dia.setFont(font)
        self.lbl_dia.setText("")
        self.lbl_dia.setObjectName("lbl_dia")
        self.TabelaAgenda_NF = QtWidgets.QTableWidget(self.centralwidget)
        self.TabelaAgenda_NF.setEnabled(True)
        self.TabelaAgenda_NF.setGeometry(QtCore.QRect(10, 130, 1351, 501))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TabelaAgenda_NF.sizePolicy().hasHeightForWidth())
        self.TabelaAgenda_NF.setSizePolicy(sizePolicy)
        self.TabelaAgenda_NF.setMinimumSize(QtCore.QSize(465, 0))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(13)
        self.TabelaAgenda_NF.setFont(font)
        self.TabelaAgenda_NF.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.TabelaAgenda_NF.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.TabelaAgenda_NF.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.TabelaAgenda_NF.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.TabelaAgenda_NF.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.TabelaAgenda_NF.setColumnCount(8)
        self.TabelaAgenda_NF.setObjectName("TabelaAgenda_NF")
        self.TabelaAgenda_NF.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaAgenda_NF.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaAgenda_NF.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaAgenda_NF.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaAgenda_NF.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaAgenda_NF.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaAgenda_NF.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaAgenda_NF.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaAgenda_NF.setHorizontalHeaderItem(7, item)
        self.TabelaAgenda_NF.horizontalHeader().setDefaultSectionSize(150)
        self.TabelaAgenda_NF.horizontalHeader().setSortIndicatorShown(False)
        self.TabelaAgenda_NF.horizontalHeader().setStretchLastSection(True)
        self.TabelaAgenda_NF.verticalHeader().setSortIndicatorShown(False)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(140, 40, 721, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(950, 0, 291, 121))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("/home/joaovitorwolfart/Dropbox/JP/PROJETO SALÃO/telas_duda/../IMAGENS/PicsArt_10-18-10.18.32.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.lbl_dia.raise_()
        self.lbl_id_user.raise_()
        self.TabelaAgenda_NF.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EMISSÃO DE NOTA FISCAL PELO AGENDAMENTO"))
        self.TabelaAgenda_NF.setSortingEnabled(False)
        item = self.TabelaAgenda_NF.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Data"))
        item = self.TabelaAgenda_NF.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Profissional"))
        item = self.TabelaAgenda_NF.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Cliente"))
        item = self.TabelaAgenda_NF.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Serviço efetuado"))
        item = self.TabelaAgenda_NF.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Fidelizado"))
        item = self.TabelaAgenda_NF.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Valor Tabela"))
        item = self.TabelaAgenda_NF.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Situação"))
        item = self.TabelaAgenda_NF.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "ID Agenda"))
        self.label_3.setText(_translate("MainWindow", "Dê um duplo clique no agendamento para Emitir a Nota Fiscal"))
