# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/jrwolfart/projetos python jv/PROJETO-SAL-O-JOVEM-PROGRAMADOR/telas_duda/vendas.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1185, 891)
        MainWindow.setMinimumSize(QtCore.QSize(1185, 891))
        MainWindow.setMaximumSize(QtCore.QSize(1185, 891))
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(215, 139, 185);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_id_user = QtWidgets.QLabel(self.centralwidget)
        self.lbl_id_user.setGeometry(QtCore.QRect(870, 10, 41, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_id_user.setFont(font)
        self.lbl_id_user.setStyleSheet("color: rgb(62, 132, 238);")
        self.lbl_id_user.setText("")
        self.lbl_id_user.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_id_user.setObjectName("lbl_id_user")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 210, 1141, 671))
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setStyleSheet("background-color: rgb(255, 231, 249);")
        self.tabWidget.setObjectName("tabWidget")
        self.tabVendas = QtWidgets.QWidget()
        self.tabVendas.setObjectName("tabVendas")
        self.label_3 = QtWidgets.QLabel(self.tabVendas)
        self.label_3.setGeometry(QtCore.QRect(40, 10, 1021, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.TabelaNfs = QtWidgets.QTableWidget(self.tabVendas)
        self.TabelaNfs.setEnabled(True)
        self.TabelaNfs.setGeometry(QtCore.QRect(10, 70, 1111, 461))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TabelaNfs.sizePolicy().hasHeightForWidth())
        self.TabelaNfs.setSizePolicy(sizePolicy)
        self.TabelaNfs.setMinimumSize(QtCore.QSize(465, 0))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(13)
        self.TabelaNfs.setFont(font)
        self.TabelaNfs.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.TabelaNfs.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.TabelaNfs.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.TabelaNfs.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.TabelaNfs.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.TabelaNfs.setObjectName("TabelaNfs")
        self.TabelaNfs.setColumnCount(7)
        self.TabelaNfs.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaNfs.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaNfs.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaNfs.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaNfs.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaNfs.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaNfs.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaNfs.setHorizontalHeaderItem(6, item)
        self.TabelaNfs.horizontalHeader().setDefaultSectionSize(150)
        self.TabelaNfs.horizontalHeader().setSortIndicatorShown(False)
        self.TabelaNfs.horizontalHeader().setStretchLastSection(True)
        self.TabelaNfs.verticalHeader().setSortIndicatorShown(False)
        self.frame_2 = QtWidgets.QFrame(self.tabVendas)
        self.frame_2.setGeometry(QtCore.QRect(10, 540, 1111, 80))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lbl_total = QtWidgets.QLabel(self.frame_2)
        self.lbl_total.setGeometry(QtCore.QRect(20, 20, 1061, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.lbl_total.setFont(font)
        self.lbl_total.setStyleSheet("color: rgb(115, 210, 22);")
        self.lbl_total.setText("")
        self.lbl_total.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_total.setObjectName("lbl_total")
        self.tabWidget.addTab(self.tabVendas, "")
        self.tabEmitidas = QtWidgets.QWidget()
        self.tabEmitidas.setObjectName("tabEmitidas")
        self.frame_3 = QtWidgets.QFrame(self.tabEmitidas)
        self.frame_3.setGeometry(QtCore.QRect(10, 520, 1111, 80))
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.lbl_total_emitidas = QtWidgets.QLabel(self.frame_3)
        self.lbl_total_emitidas.setGeometry(QtCore.QRect(20, 20, 1061, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.lbl_total_emitidas.setFont(font)
        self.lbl_total_emitidas.setStyleSheet("color: rgb(115, 210, 22);")
        self.lbl_total_emitidas.setText("")
        self.lbl_total_emitidas.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_total_emitidas.setObjectName("lbl_total_emitidas")
        self.TabelaEmitidas = QtWidgets.QTableWidget(self.tabEmitidas)
        self.TabelaEmitidas.setEnabled(True)
        self.TabelaEmitidas.setGeometry(QtCore.QRect(10, 60, 1111, 451))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TabelaEmitidas.sizePolicy().hasHeightForWidth())
        self.TabelaEmitidas.setSizePolicy(sizePolicy)
        self.TabelaEmitidas.setMinimumSize(QtCore.QSize(465, 0))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(13)
        self.TabelaEmitidas.setFont(font)
        self.TabelaEmitidas.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.TabelaEmitidas.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.TabelaEmitidas.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.TabelaEmitidas.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.TabelaEmitidas.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.TabelaEmitidas.setObjectName("TabelaEmitidas")
        self.TabelaEmitidas.setColumnCount(7)
        self.TabelaEmitidas.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaEmitidas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaEmitidas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaEmitidas.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaEmitidas.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaEmitidas.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaEmitidas.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaEmitidas.setHorizontalHeaderItem(6, item)
        self.TabelaEmitidas.horizontalHeader().setDefaultSectionSize(150)
        self.TabelaEmitidas.horizontalHeader().setSortIndicatorShown(False)
        self.TabelaEmitidas.horizontalHeader().setStretchLastSection(True)
        self.TabelaEmitidas.verticalHeader().setSortIndicatorShown(False)
        self.label_4 = QtWidgets.QLabel(self.tabEmitidas)
        self.label_4.setGeometry(QtCore.QRect(40, 0, 1021, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.tabWidget.addTab(self.tabEmitidas, "")
        self.tabPendentes = QtWidgets.QWidget()
        self.tabPendentes.setObjectName("tabPendentes")
        self.frame_4 = QtWidgets.QFrame(self.tabPendentes)
        self.frame_4.setGeometry(QtCore.QRect(20, 540, 1101, 80))
        self.frame_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.lbl_total_pendentes = QtWidgets.QLabel(self.frame_4)
        self.lbl_total_pendentes.setGeometry(QtCore.QRect(20, 20, 1061, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.lbl_total_pendentes.setFont(font)
        self.lbl_total_pendentes.setStyleSheet("color: rgb(115, 210, 22);")
        self.lbl_total_pendentes.setText("")
        self.lbl_total_pendentes.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_total_pendentes.setObjectName("lbl_total_pendentes")
        self.TabelaPendentes = QtWidgets.QTableWidget(self.tabPendentes)
        self.TabelaPendentes.setEnabled(True)
        self.TabelaPendentes.setGeometry(QtCore.QRect(20, 70, 1101, 451))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TabelaPendentes.sizePolicy().hasHeightForWidth())
        self.TabelaPendentes.setSizePolicy(sizePolicy)
        self.TabelaPendentes.setMinimumSize(QtCore.QSize(465, 0))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(13)
        self.TabelaPendentes.setFont(font)
        self.TabelaPendentes.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.TabelaPendentes.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.TabelaPendentes.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.TabelaPendentes.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.TabelaPendentes.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.TabelaPendentes.setObjectName("TabelaPendentes")
        self.TabelaPendentes.setColumnCount(7)
        self.TabelaPendentes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaPendentes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaPendentes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaPendentes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaPendentes.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaPendentes.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaPendentes.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaPendentes.setHorizontalHeaderItem(6, item)
        self.TabelaPendentes.horizontalHeader().setDefaultSectionSize(150)
        self.TabelaPendentes.horizontalHeader().setSortIndicatorShown(False)
        self.TabelaPendentes.horizontalHeader().setStretchLastSection(True)
        self.TabelaPendentes.verticalHeader().setSortIndicatorShown(False)
        self.label_5 = QtWidgets.QLabel(self.tabPendentes)
        self.label_5.setGeometry(QtCore.QRect(50, 10, 1021, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.tabPendentes, "")
        self.tabCanceladas = QtWidgets.QWidget()
        self.tabCanceladas.setObjectName("tabCanceladas")
        self.frame_5 = QtWidgets.QFrame(self.tabCanceladas)
        self.frame_5.setGeometry(QtCore.QRect(10, 530, 1111, 80))
        self.frame_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.lbl_total_canceladas = QtWidgets.QLabel(self.frame_5)
        self.lbl_total_canceladas.setGeometry(QtCore.QRect(20, 20, 1061, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.lbl_total_canceladas.setFont(font)
        self.lbl_total_canceladas.setStyleSheet("color: rgb(115, 210, 22);")
        self.lbl_total_canceladas.setText("")
        self.lbl_total_canceladas.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_total_canceladas.setObjectName("lbl_total_canceladas")
        self.TabelaCanceladas = QtWidgets.QTableWidget(self.tabCanceladas)
        self.TabelaCanceladas.setEnabled(True)
        self.TabelaCanceladas.setGeometry(QtCore.QRect(10, 70, 1111, 441))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TabelaCanceladas.sizePolicy().hasHeightForWidth())
        self.TabelaCanceladas.setSizePolicy(sizePolicy)
        self.TabelaCanceladas.setMinimumSize(QtCore.QSize(465, 0))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(13)
        self.TabelaCanceladas.setFont(font)
        self.TabelaCanceladas.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.TabelaCanceladas.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.TabelaCanceladas.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.TabelaCanceladas.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.TabelaCanceladas.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.TabelaCanceladas.setObjectName("TabelaCanceladas")
        self.TabelaCanceladas.setColumnCount(7)
        self.TabelaCanceladas.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaCanceladas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaCanceladas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaCanceladas.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaCanceladas.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaCanceladas.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaCanceladas.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TabelaCanceladas.setHorizontalHeaderItem(6, item)
        self.TabelaCanceladas.horizontalHeader().setDefaultSectionSize(150)
        self.TabelaCanceladas.horizontalHeader().setSortIndicatorShown(False)
        self.TabelaCanceladas.horizontalHeader().setStretchLastSection(True)
        self.TabelaCanceladas.verticalHeader().setSortIndicatorShown(False)
        self.tabWidget.addTab(self.tabCanceladas, "")
        self.RbData = QtWidgets.QRadioButton(self.centralwidget)
        self.RbData.setGeometry(QtCore.QRect(210, 70, 181, 28))
        self.RbData.setObjectName("RbData")
        self.RbTodas = QtWidgets.QRadioButton(self.centralwidget)
        self.RbTodas.setGeometry(QtCore.QRect(50, 70, 151, 28))
        self.RbTodas.setChecked(True)
        self.RbTodas.setObjectName("RbTodas")
        self.RbCliente = QtWidgets.QRadioButton(self.centralwidget)
        self.RbCliente.setGeometry(QtCore.QRect(400, 70, 121, 28))
        self.RbCliente.setObjectName("RbCliente")
        self.BtnNVenda = QtWidgets.QPushButton(self.centralwidget)
        self.BtnNVenda.setGeometry(QtCore.QRect(950, 60, 151, 51))
        self.BtnNVenda.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BtnNVenda.setStyleSheet("QPushButton {     \n"
"    background-color:rgb(78, 154, 6);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    \n"
"}\n"
"QPushButton:hover {   \n"
"    background-color:rgb(85, 165, 10);\n"
"}\n"
"")
        self.BtnNVenda.setObjectName("BtnNVenda")
        self.lbl_escolha = QtWidgets.QLabel(self.centralwidget)
        self.lbl_escolha.setGeometry(QtCore.QRect(50, 140, 1061, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_escolha.setFont(font)
        self.lbl_escolha.setText("")
        self.lbl_escolha.setObjectName("lbl_escolha")
        self.RbIntervaloDatas = QtWidgets.QRadioButton(self.centralwidget)
        self.RbIntervaloDatas.setGeometry(QtCore.QRect(760, 70, 171, 28))
        self.RbIntervaloDatas.setObjectName("RbIntervaloDatas")
        self.RbIntervaloNotas = QtWidgets.QRadioButton(self.centralwidget)
        self.RbIntervaloNotas.setGeometry(QtCore.QRect(530, 70, 221, 28))
        self.RbIntervaloNotas.setObjectName("RbIntervaloNotas")
        self.lbl_status_2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_status_2.setGeometry(QtCore.QRect(130, 10, 801, 41))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.lbl_status_2.setFont(font)
        self.lbl_status_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_status_2.setObjectName("lbl_status_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Vendas e faturamento"))
        self.label_3.setText(_translate("MainWindow", "Dê um duplo clique na nota fiscal para ver os itens ou para alterar caso esteja pendente."))
        self.TabelaNfs.setSortingEnabled(False)
        item = self.TabelaNfs.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "N° de NF"))
        item = self.TabelaNfs.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Data da venda"))
        item = self.TabelaNfs.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "ID do cliente"))
        item = self.TabelaNfs.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Cliente"))
        item = self.TabelaNfs.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Valor"))
        item = self.TabelaNfs.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Fidelizado"))
        item = self.TabelaNfs.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Status da NF"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabVendas), _translate("MainWindow", "Todas as notas"))
        self.TabelaEmitidas.setSortingEnabled(False)
        item = self.TabelaEmitidas.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "N° de NF"))
        item = self.TabelaEmitidas.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Data da venda"))
        item = self.TabelaEmitidas.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "ID do cliente"))
        item = self.TabelaEmitidas.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Cliente"))
        item = self.TabelaEmitidas.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Valor"))
        item = self.TabelaEmitidas.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Fidelizado"))
        item = self.TabelaEmitidas.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Status"))
        self.label_4.setText(_translate("MainWindow", "Dê um duplo clique na nota fiscal para ver os itens ou cancelar a nota."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabEmitidas), _translate("MainWindow", "Notas emitidas"))
        self.TabelaPendentes.setSortingEnabled(False)
        item = self.TabelaPendentes.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "N° de NF"))
        item = self.TabelaPendentes.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Data da venda"))
        item = self.TabelaPendentes.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "ID do cliente"))
        item = self.TabelaPendentes.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Cliente"))
        item = self.TabelaPendentes.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Valor"))
        item = self.TabelaPendentes.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Fidelizado"))
        item = self.TabelaPendentes.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Status"))
        self.label_5.setText(_translate("MainWindow", "Dê um duplo clique na nota fiscal para concluir, incluir itens ou cancelar a nota"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPendentes), _translate("MainWindow", "Notas pendentes"))
        self.TabelaCanceladas.setSortingEnabled(False)
        item = self.TabelaCanceladas.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "N° de NF"))
        item = self.TabelaCanceladas.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Data da venda"))
        item = self.TabelaCanceladas.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "ID do cliente"))
        item = self.TabelaCanceladas.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Cliente"))
        item = self.TabelaCanceladas.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Valor"))
        item = self.TabelaCanceladas.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Fidelizado"))
        item = self.TabelaCanceladas.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Status"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCanceladas), _translate("MainWindow", "Notas canceladas"))
        self.RbData.setText(_translate("MainWindow", "Por data da venda"))
        self.RbTodas.setText(_translate("MainWindow", "Todas as notas"))
        self.RbCliente.setText(_translate("MainWindow", "Por cliente"))
        self.BtnNVenda.setText(_translate("MainWindow", "Nova venda"))
        self.RbIntervaloDatas.setText(_translate("MainWindow", "Por intervalo de datas"))
        self.RbIntervaloNotas.setText(_translate("MainWindow", "Por intervalo de notas"))
        self.lbl_status_2.setText(_translate("MainWindow", "Vendas e Faturamento"))
